# Generated by Django 6.1 on 2026-08-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='characters.character')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='characters.character')),
            ],
        ),
    ]
