# Generated by Django 6.1 on 2026-08-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='quoted_text',
            field=models.TextField(blank=True),
        ),
    ]
