# Generated by Django 6.1 on 2026-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_chapterversion'),
        ('characters', '0002_relationship'),
        ('evidence', '0001_initial'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='related_characters',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='characters.character'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='related_events',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='timeline.timelineevent'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='related_evidence',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='evidence.evidence'),
        ),
    ]
