# Generated by Django 6.1 on 2026-08-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('character', 'Character'), ('evidence', 'Evidence'), ('event', 'Event'), ('note', 'Note')], max_length=20)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note_text', models.TextField(blank=True)),
                ('x', models.FloatField(default=100)),
                ('y', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_items', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BoardConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_connections', to='projects.project')),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='board.boarditem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='board.boarditem')),
            ],
        ),
    ]
