# Generated by Django 6.1 on 2026-08-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('projects', '0002_projectmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('found_location', models.CharField(blank=True, max_length=255)),
                ('is_real', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='projects.project')),
                ('related_characters', models.ManyToManyField(blank=True, related_name='evidence_items', to='characters.character')),
            ],
        ),
    ]
